################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl.c \
D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_convert.c \
D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_image_io.c \
D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_mem_alloc.c \
D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_resize.c \
D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/umm_malloc.c 

OBJS += \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.o \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.o \
./Middlewares/STM32_ImageProcessing_Library/umm_malloc.o 

C_DEPS += \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.d \
./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.d \
./Middlewares/STM32_ImageProcessing_Library/umm_malloc.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_ImageProcessing_Library/stm32ipl.o: D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DMEMORY_SCHEME=3 -DCAMERA_CAPTURE_RES=2 -DPIXEL_FMT_CONV=1 -DSTM32IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1 -c -I../../../CM7/Inc -I../../../../../Common/CM7/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32H747I-Discovery -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/ov9655 -I../../../../../../../../Drivers/BSP/Components/otm8009a -I../../../../../../../../Utilities/Fonts -I../../../../../../../../Utilities/lcd -I../../../../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../../../../Middlewares/ST/STM32_AI_Utilities/Inc -I../../../../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../../../../Middlewares/Third_Party/FatFs/src -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.o: D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_convert.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DMEMORY_SCHEME=3 -DCAMERA_CAPTURE_RES=2 -DPIXEL_FMT_CONV=1 -DSTM32IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1 -c -I../../../CM7/Inc -I../../../../../Common/CM7/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32H747I-Discovery -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/ov9655 -I../../../../../../../../Drivers/BSP/Components/otm8009a -I../../../../../../../../Utilities/Fonts -I../../../../../../../../Utilities/lcd -I../../../../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../../../../Middlewares/ST/STM32_AI_Utilities/Inc -I../../../../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../../../../Middlewares/Third_Party/FatFs/src -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.o: D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_image_io.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DMEMORY_SCHEME=3 -DCAMERA_CAPTURE_RES=2 -DPIXEL_FMT_CONV=1 -DSTM32IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1 -c -I../../../CM7/Inc -I../../../../../Common/CM7/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32H747I-Discovery -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/ov9655 -I../../../../../../../../Drivers/BSP/Components/otm8009a -I../../../../../../../../Utilities/Fonts -I../../../../../../../../Utilities/lcd -I../../../../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../../../../Middlewares/ST/STM32_AI_Utilities/Inc -I../../../../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../../../../Middlewares/Third_Party/FatFs/src -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.o: D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_mem_alloc.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DMEMORY_SCHEME=3 -DCAMERA_CAPTURE_RES=2 -DPIXEL_FMT_CONV=1 -DSTM32IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1 -c -I../../../CM7/Inc -I../../../../../Common/CM7/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32H747I-Discovery -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/ov9655 -I../../../../../../../../Drivers/BSP/Components/otm8009a -I../../../../../../../../Utilities/Fonts -I../../../../../../../../Utilities/lcd -I../../../../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../../../../Middlewares/ST/STM32_AI_Utilities/Inc -I../../../../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../../../../Middlewares/Third_Party/FatFs/src -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.o: D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/stm32ipl_resize.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DMEMORY_SCHEME=3 -DCAMERA_CAPTURE_RES=2 -DPIXEL_FMT_CONV=1 -DSTM32IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1 -c -I../../../CM7/Inc -I../../../../../Common/CM7/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32H747I-Discovery -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/ov9655 -I../../../../../../../../Drivers/BSP/Components/otm8009a -I../../../../../../../../Utilities/Fonts -I../../../../../../../../Utilities/lcd -I../../../../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../../../../Middlewares/ST/STM32_AI_Utilities/Inc -I../../../../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../../../../Middlewares/Third_Party/FatFs/src -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ImageProcessing_Library/umm_malloc.o: D:/Projects/FP-AI-VISION1_V3.1.0/Middlewares/ST/STM32_ImageProcessing_Library/Src/umm_malloc.c Middlewares/STM32_ImageProcessing_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DDATA_IN_ExtSDRAM -DMEMORY_SCHEME=3 -DCAMERA_CAPTURE_RES=2 -DPIXEL_FMT_CONV=1 -DSTM32IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1 -c -I../../../CM7/Inc -I../../../../../Common/CM7/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32H747I-Discovery -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/ov9655 -I../../../../../../../../Drivers/BSP/Components/otm8009a -I../../../../../../../../Utilities/Fonts -I../../../../../../../../Utilities/lcd -I../../../../../../../../Middlewares/ST/STM32_AI_Runtime/Inc -I../../../../../../../../Middlewares/ST/STM32_AI_Utilities/Inc -I../../../../../../../../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../../../../../../../../Middlewares/Third_Party/FatFs/src -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-STM32_ImageProcessing_Library

clean-Middlewares-2f-STM32_ImageProcessing_Library:
	-$(RM) ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_convert.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_image_io.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_mem_alloc.su ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.cyclo ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.d ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.o ./Middlewares/STM32_ImageProcessing_Library/stm32ipl_resize.su ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.cyclo ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.d ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.o ./Middlewares/STM32_ImageProcessing_Library/umm_malloc.su

.PHONY: clean-Middlewares-2f-STM32_ImageProcessing_Library

